#############################################
# PASOS INDISPENSABLES PARA EL USO DE DOCKER#
#############################################

# chmod 600 ./docker/ssh/id_rsa
# docker exec -it -u appuser top-symfony-be bin/console <instrucción>

version: '3.5'

services:
  top-symfony-web:
    container_name: top-symfony-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./backend/public:/appdata/www/public
    depends_on:
      - top-symfony-be
    networks:
      - top-symfony-network

  top-symfony-be:
    container_name: top-symfony-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # Linux users
    #      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005 # MacOS users
    volumes:
      - ./backend/:/appdata/www/
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      #      - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - top-symfony-db
    networks:
      - top-symfony-network

  top-symfony-db:
    container_name: top-symfony-db
    image: mysql:8.0
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - top-symfony-db-data:/var/lib/mysql
    networks:
      - top-symfony-network

  top-angular-frontend:
    container_name: top-angular-frontend
    image: 'my-angular-app'
    build: '.'
    ports:
      - 3000:80

volumes:
  top-symfony-db-data:

networks:
  top-symfony-network:
    external: true
